<a href="https://colab.research.google.com/github/sudeepbhagat11/ML-LAB-102217257/blob/main/ML_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Q1 a)

In [ ]:
import numpy as np

arr = [1,2,3,6,5,4]

In [ ]:
print(arr)

[1, 2, 3, 6, 5, 4]


In [ ]:
print(np.flip(arr))

[4 5 6 3 2 1]


#b)

In [ ]:
a = np.array([[1,2], [3,4]])

In [ ]:
a.flatten()

array([1, 2, 3, 4])

# Q1. c)

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,2],[3,4]])

In [ ]:
print(np.equal(a, b))
# print(a==b)

[[ True  True]
 [ True  True]]


# Q1. D)

In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

In [ ]:
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
indices = np.where(x == most_frequent_value)[0]



In [ ]:
print(indices)
print(most_frequent_value)

[0 5 7 8 9]
1


# Q1. E)

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [ ]:
np.sum(gfg)

45

In [ ]:
np.sum(gfg, axis=1)

matrix([[14],
        [16],
        [15]])

In [ ]:
np.sum(gfg, axis=0)

matrix([[20,  9, 16]])

# Q1. F)

In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.diag(n_array))

[55 44 77]


In [ ]:
w, v = np.linalg.eig(n_array)

In [ ]:
print('Eogen Values : ', w)
print('Eigen Vectors : ', v)

Eogen Values :  [98.16835147 28.097044   49.73460452]
Eigen Vectors :  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
print('Inverse Matrix is : ', np.linalg.inv(n_array) )

Inverse Matrix is :  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
print('Determinant of Matrix is : ', np.linalg.det(n_array) )

Determinant of Matrix is :  137180.0000000001


# Q1. G)

In [ ]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

print(np.dot(p, q))
print(np.cov(p, q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = np.array([[1, 2], [2, 3], [4,5]])
q = np.array([[4, 5, 1], [6, 7, 2]])

print(np.dot(p, q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
# Flatten both arrays
p_flat = p.flatten()
q_flat = q.flatten()

# Ensure they have the same length
min_length = min(len(p_flat), len(q_flat))
p_flat = p_flat[:min_length]
q_flat = q_flat[:min_length]

# Calculate the covariance
cov_matrix = np.cov(p_flat, q_flat)
print("Covariance matrix:\n", cov_matrix)



Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
x = np.array([[2, 3, 4], [3,2,9]])
y = np.array([[1,5,0], [5,10,3]])


np.inner(x,y)


array([[17, 52],
       [13, 62]])

In [ ]:
np.outer(x,y)


array([[ 2, 10,  0, 10, 20,  6],
       [ 3, 15,  0, 15, 30,  9],
       [ 4, 20,  0, 20, 40, 12],
       [ 3, 15,  0, 15, 30,  9],
       [ 2, 10,  0, 10, 20,  6],
       [ 9, 45,  0, 45, 90, 27]])

In [ ]:
# Building the Cartesian product
a_tiled = np.tile(x, (len(y), 1))
b_repeated = np.repeat(y, len(x), axis=0)
c = np.hstack((a_tiled, b_repeated))

# Printing results
print(c)

[[ 2  3  4  1  5  0]
 [ 3  2  9  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  5 10  3]]


# 2.

In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
#i
print(np.absolute(array))
print('\n')

[[1 2 3]
 [4 5 6]]




In [ ]:


# ii)Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
print("25th percentile of flattened array: ", np.percentile(array, 25))
print("50th percentile of flattened array: ", np.percentile(array, 50))
print("75th percentile of flattened array: ", np.percentile(array, 75))
print('\n')
print("25th percentile of 1st column: ", np.percentile(array, 25, axis=0))
print("50th percentile of 2nd column: ", np.percentile(array, 50, axis=0))
print("75th percentile of 3rd  column: ", np.percentile(array, 75, axis=0))
print('\n')
print("25th percentile of 1st row: ", np.percentile(array, 25, axis=1))
print("50th percentile of 2nd row: ", np.percentile(array, 50, axis=1))
print("75th percentile of 3rd row: ", np.percentile(array, 75, axis=1))


25th percentile of flattened array:  -3.5
50th percentile of flattened array:  -0.5
75th percentile of flattened array:  2.5


25th percentile of 1st column:  [-2.75 -0.25 -3.75]
50th percentile of 2nd column:  [-1.5  1.5 -1.5]
75th percentile of 3rd  column:  [-0.25  3.25  0.75]


25th percentile of 1st row:  [-0.5 -5. ]
50th percentile of 2nd row:  [ 1. -4.]
75th percentile of 3rd row:  [2.  0.5]


In [ ]:
#Mean, Median and Standard Deviation of flattened array, of each column, and each row

print("Mean of flattened array: ", np.mean(array))
print("Median of flattened array: ", np.median(array))
print("Standard Deviation of flattened array: ", np.std(array))
print('\n')
print("Mean of 1st column: ", np.mean(array,axis=0))
print("Median of 2nd column: ", np.median(array,axis=0))
print("Standard Deviation of 3rd  column: ", np.std(array, axis=0))
print('\n')
print("Mean of 1st row: ", np.mean(array, axis=1))
print("Median of 2nd row: ", np.median(array,axis=1))
print("Standard Deviation of 3rd row: ", np.std(array,axis=1))



Mean of flattened array:  -0.5
Median of flattened array:  -0.5
Standard Deviation of flattened array:  3.8622100754188224


Mean of 1st column:  [-1.5  1.5 -1.5]
Median of 2nd column:  [-1.5  1.5 -1.5]
Standard Deviation of 3rd  column:  [2.5 3.5 4.5]


Mean of 1st row:  [ 0.66666667 -1.66666667]
Median of 2nd row:  [ 1. -4.]
Standard Deviation of 3rd row:  [2.05480467 4.78423336]


In [ ]:
# b.)
a=np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print('\n')
print(np.ceil(a))
print('\n')
print(np.trunc(a))
print('\n')
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]


[-1. -1. -0.  1.  2.  2.  3.]


[-1. -1. -0.  0.  1.  1.  3.]


[-2. -2. -0.  0.  2.  2.  3.]


# 3.

In [ ]:
#i
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))

[ 10  16  16  52  54  62 453]


In [ ]:
#ii
print('The indices of sorted arry with respect to its original arry is:')
print(np.argsort(array))

The indices of sorted arry with respect to its original arry is:
[0 3 4 1 5 2 6]


In [ ]:
#iii
print('Four smallest number are:')
print(np.sort(array)[:4])

Four smallest number are:
[10 16 16 52]


In [ ]:
#iv
print('Five largest number in ascending order  are:')
print(np.sort(array)[-5:])

Five largest number in ascending order  are:
[ 16  52  54  62 453]


In [1]:
#Q4
import cv2
import numpy as np

def img_to_array(path):
    image = cv2.imread(path)
    if image is None:
        print("Error: Image not found at the specified path.")
        return
    if (len(image.shape) == 2):
        image_type = 'grayscale'
        array = image
    else:
        image_type = 'RGB'
        array = image

    array_str = np.array2string(array, separator=',', formatter={'float_kind': lambda x: "%.2f" % x})

    if image_type == 'grayscale':
        text_file_path = path.replace('.jpg', '_grayscale.txt').replace('.png', '_grayscale.txt')
    else:
        text_file_path = path.replace('.jpg', '_RGB.txt').replace('.png', '_RGB.txt')

    with open(text_file_path, 'w') as file:
        file.write(array_str)

    print(f"The {image_type} image has been saved as a text file at: {text_file_path}")

img_to_array("/content/ai.jpg")


The RGB image has been saved as a text file at: /content/ai_RGB.txt


In [2]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

np.savetxt('array.txt', array, delimiter=',', fmt='%d')

loaded_array = np.loadtxt('array.txt', delimiter=',')
print(loaded_array)


[[ 1. -2.  3.]
 [-4.  5. -6.]]
